/**
 * TOOLS-013 (#49) -- Webhook receiver
 *
 * Types and utilities for receiving, validating, and processing inbound
 * webhooks. Supports HMAC-SHA256 signature verification, IP allowlisting,
 * and structured event parsing.
 *
 * @module
 */

import { createHmac, timingSafeEqual } from "node:crypto";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/** Configuration for a webhook endpoint. */
export type WebhookConfig = {
  /**
   * URL path this webhook listens on (e.g. `"/webhooks/github"`).
   * Must start with `/`.
   */
  path: string;

  /**
   * Shared secret used for HMAC signature verification.
   * Stored as a vault reference in production; may be a literal string
   * in development.
   */
  secret: string;

  /**
   * IP addresses or CIDR ranges allowed to send webhooks to this endpoint.
   * When empty, all source IPs are permitted (signature verification
   * is still enforced).
   */
  allowed_ips: string[];

  /** Human-readable label for this webhook (e.g. `"GitHub push events"`). */
  label?: string;

  /** Whether this webhook endpoint is currently enabled. */
  enabled?: boolean;
};

// ---------------------------------------------------------------------------
// Event
// ---------------------------------------------------------------------------

/** A received webhook event. */
export type WebhookEvent = {
  /** Unique event ID (generated by the receiver, not the sender). */
  id: string;

  /**
   * Source identifier.
   * May be a service name (e.g. `"github"`, `"stripe"`) or the sender's
   * IP address when the source cannot be determined.
   */
  source: string;

  /**
   * The raw request body, parsed as a JSON object.
   * For non-JSON payloads this will be `{ raw: "<base64-encoded body>" }`.
   */
  payload: Record<string, unknown>;

  /**
   * The signature header value sent by the webhook source.
   * Typically an HMAC-SHA256 hex digest (e.g. `"sha256=abc123..."`)
   * or a bare hex string.
   */
  signature: string;

  /** ISO-8601 timestamp of when the event was received. */
  received_at: string;

  /** HTTP method of the incoming request (usually `"POST"`). */
  method?: string;

  /**
   * HTTP headers from the incoming request (lowercased keys).
   * Useful for provider-specific metadata (e.g. `x-github-event`).
   */
  headers?: Record<string, string>;

  /** Source IP address of the sender. */
  source_ip?: string;
};

// ---------------------------------------------------------------------------
// Signature verification
// ---------------------------------------------------------------------------

/**
 * Verify the HMAC-SHA256 signature of a webhook event.
 *
 * Supports two common header formats:
 * - Prefixed: `"sha256=<hex>"` (GitHub, Shopify)
 * - Bare hex: `"<hex>"` (Stripe, generic)
 *
 * Uses constant-time comparison to prevent timing attacks.
 *
 * @param event  The received webhook event.
 * @param secret The shared secret for this endpoint.
 * @returns `true` when the signature is valid, `false` otherwise.
 */
export function verifyWebhookSignature(event: WebhookEvent, secret: string): boolean {
  const body = JSON.stringify(event.payload);
  const expectedHmac = createHmac("sha256", secret).update(body, "utf8").digest("hex");

  // Strip the `sha256=` prefix if present.
  const provided = event.signature.startsWith("sha256=")
    ? event.signature.slice("sha256=".length)
    : event.signature;

  // Constant-time comparison.
  const expectedBuf = Buffer.from(expectedHmac, "hex");
  const providedBuf = Buffer.from(provided, "hex");

  if (expectedBuf.length !== providedBuf.length) return false;

  return timingSafeEqual(expectedBuf, providedBuf);
}

// ---------------------------------------------------------------------------
// IP check
// ---------------------------------------------------------------------------

/**
 * Check whether a source IP is permitted by the webhook config.
 *
 * @returns `true` when the IP is allowed (or the allowlist is empty).
 */
export function isIpAllowed(config: WebhookConfig, sourceIp: string): boolean {
  if (config.allowed_ips.length === 0) return true;

  // TODO: support CIDR range matching
  return config.allowed_ips.includes(sourceIp);
}
