pre-commit:
  parallel: true
  commands:
    lint:
      run: pnpm tsgo && pnpm lint
      stage_fixed: true
    changeset-check:
      run: bash .claude/scripts/check-changeset.sh

commit-msg:
  commands:
    commitlint:
      run: npx commitlint --edit "{1}"

pre-push:
  parallel: true
  commands:
    test:
      run: pnpm test
    build:
      run: pnpm build
