export const browserCoreExamples = [
  "zoidbergbot browser status",
  "zoidbergbot browser start",
  "zoidbergbot browser stop",
  "zoidbergbot browser tabs",
  "zoidbergbot browser open https://example.com",
  "zoidbergbot browser focus abcd1234",
  "zoidbergbot browser close abcd1234",
  "zoidbergbot browser screenshot",
  "zoidbergbot browser screenshot --full-page",
  "zoidbergbot browser screenshot --ref 12",
  "zoidbergbot browser snapshot",
  "zoidbergbot browser snapshot --format aria --limit 200",
  "zoidbergbot browser snapshot --efficient",
  "zoidbergbot browser snapshot --labels",
];

export const browserActionExamples = [
  "zoidbergbot browser navigate https://example.com",
  "zoidbergbot browser resize 1280 720",
  "zoidbergbot browser click 12 --double",
  'zoidbergbot browser type 23 "hello" --submit',
  "zoidbergbot browser press Enter",
  "zoidbergbot browser hover 44",
  "zoidbergbot browser drag 10 11",
  "zoidbergbot browser select 9 OptionA OptionB",
  "zoidbergbot browser upload /tmp/file.pdf",
  'zoidbergbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "zoidbergbot browser dialog --accept",
  'zoidbergbot browser wait --text "Done"',
  "zoidbergbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "zoidbergbot browser console --level error",
  "zoidbergbot browser pdf",
];
