name: ZoidbergBot
options:
  bundleIdPrefix: ai.zoidbergbot
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  ZoidbergBotKit:
    path: ../shared/ZoidbergBotKit
  Swabble:
    path: ../../Swabble

schemes:
  ZoidbergBot:
    shared: true
    build:
      targets:
        ZoidbergBot: all
    test:
      targets:
        - ZoidbergBotTests

targets:
  ZoidbergBot:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: ZoidbergBotKit
      - package: ZoidbergBotKit
        product: ZoidbergBotChatUI
      - package: ZoidbergBotKit
        product: ZoidbergBotProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Y5PE65HELJ
        PRODUCT_BUNDLE_IDENTIFIER: ai.zoidbergbot.ios
        PROVISIONING_PROFILE_SPECIFIER: "ai.zoidbergbot.ios Development"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: ZoidbergBot
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: "2026.1.27-beta.1"
        CFBundleVersion: "20260126"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
        NSLocalNetworkUsageDescription: ZoidbergBot discovers and connects to your ZoidbergBot gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _zoidbergbot-gw._tcp
        NSCameraUsageDescription: ZoidbergBot can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: ZoidbergBot uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: ZoidbergBot can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: ZoidbergBot needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: ZoidbergBot uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  ZoidbergBotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: ZoidbergBot
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.zoidbergbot.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ZoidbergBot.app/ZoidbergBot"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: ZoidbergBotTests
        CFBundleShortVersionString: "2026.1.27-beta.1"
        CFBundleVersion: "20260126"
