#!/usr/bin/env python3
"""
Sync parsed PPTX community data to Twenty CRM

Usage:
    pptx_parser.py parse-community file.pptx | sync_to_twenty.py
    sync_to_twenty.py --file community_data.json
    sync_to_twenty.py --dry-run < community_data.json
"""

import argparse
import json
import os
import sys
from datetime import datetime
from typing import Optional

import requests


class TwentyCRM:
    """Twenty CRM API client for One Point Partners"""
    
    def __init__(self, api_url: str, api_token: str):
        self.api_url = api_url.rstrip("/")
        self.headers = {
            "Authorization": f"Bearer {api_token}",
            "Content-Type": "application/json"
        }
    
    def _request(self, method: str, endpoint: str, data: dict = None) -> dict:
        """Make API request"""
        url = f"{self.api_url}/rest/{endpoint}"
        resp = requests.request(method, url, headers=self.headers, json=data)
        
        if resp.status_code >= 400:
            raise Exception(f"API error {resp.status_code}: {resp.text}")
        
        return resp.json() if resp.text else {}
    
    # === Engagements ===
    
    def search_engagements(self, name: str) -> list:
        """Search for engagements by name"""
        resp = self._request("GET", "engagements")
        engagements = resp.get("data", {}).get("engagements", [])
        # Filter by name (case-insensitive partial match)
        name_lower = name.lower()
        return [e for e in engagements if name_lower in e.get("name", "").lower()]
    
    def update_engagement(self, engagement_id: str, data: dict) -> dict:
        """Update existing engagement"""
        resp = self._request("PATCH", f"engagements/{engagement_id}", data)
        return resp.get("data", {}).get("updateEngagement", {})
    
    # === Communities ===
    
    def search_communities(self, name: str) -> list:
        """Search for communities by name"""
        resp = self._request("GET", "communities")
        communities = resp.get("data", {}).get("communities", [])
        name_lower = name.lower()
        return [c for c in communities if name_lower in c.get("name", "").lower()]
    
    # === Workspace Members ===
    
    def get_workspace_members(self) -> list:
        """Get all workspace members"""
        resp = self._request("GET", "workspaceMembers")
        return resp.get("data", {}).get("workspaceMembers", [])
    
    def find_member_by_name(self, first_name: str) -> Optional[str]:
        """Find workspace member ID by first name"""
        members = self.get_workspace_members()
        for m in members:
            if m.get("name", {}).get("firstName", "").lower() == first_name.lower():
                return m.get("id")
        return None
    
    # === People ===
    
    def search_people(self, email: str = None) -> list:
        """Search for people by email"""
        resp = self._request("GET", "people")
        people = resp.get("data", {}).get("people", [])
        if email:
            return [p for p in people if p.get("emails", {}).get("primaryEmail") == email]
        return people
    
    def create_person(self, first_name: str, last_name: str, email: str, job_title: str = "") -> dict:
        """Create a new person/contact"""
        data = {
            "name": {"firstName": first_name, "lastName": last_name},
            "emails": {"primaryEmail": email},
            "jobTitle": job_title
        }
        resp = self._request("POST", "people", data)
        return resp.get("data", {}).get("createPerson", {})
    
    # === Notes ===
    
    def create_note(self, title: str, markdown: str) -> dict:
        """Create a note with markdown content"""
        data = {
            "title": title,
            "bodyV2": {
                "blocknote": "",  # Auto-generated by Twenty
                "markdown": markdown
            }
        }
        resp = self._request("POST", "notes", data)
        return resp.get("data", {}).get("createNote", {})
    
    def link_note_to_engagement(self, note_id: str, engagement_id: str) -> dict:
        """Link a note to an engagement via noteTargets"""
        data = {
            "noteId": note_id,
            "engagementId": engagement_id
        }
        resp = self._request("POST", "noteTargets", data)
        return resp.get("data", {}).get("createNoteTarget", {})


def sync_community_to_twenty(community_data: dict, crm: TwentyCRM, dry_run: bool = False) -> dict:
    """
    Sync parsed community data to Twenty CRM
    
    Creates/updates:
    - Engagement record (links manager, community)
    - People records for contacts
    - Notes for team, goals, market analysis, etc.
    """
    results = {
        "engagement": None,
        "contacts_created": [],
        "notes_created": [],
        "notes_linked": [],
        "errors": []
    }
    
    community_name = community_data.get("name", "Unknown Community")
    
    if dry_run:
        print(f"[DRY RUN] Would sync: {community_name}")
        print(json.dumps(community_data, indent=2))
        return results
    
    # 1. Find engagement
    print(f"Searching for engagement: {community_name}")
    engagements = crm.search_engagements(community_name)
    
    if not engagements:
        results["errors"].append(f"No engagement found for: {community_name}")
        print(f"ERROR: No engagement found. Create one in Twenty first.")
        return results
    
    engagement = engagements[0]
    engagement_id = engagement.get("id")
    print(f"Found engagement: {engagement_id}")
    results["engagement"] = {"id": engagement_id, "name": engagement.get("name")}
    
    # 2. Find community record
    communities = crm.search_communities(community_name)
    community_id = communities[0].get("id") if communities else None
    
    # 3. Find engagement manager from parsed team
    manager_id = None
    team = community_data.get("one_point_team", [])
    for member in team:
        if "manager" in member.get("role", "").lower():
            manager_id = crm.find_member_by_name(member.get("name", ""))
            if manager_id:
                print(f"Found manager: {member.get('name')} ({manager_id})")
                break
    
    # 4. Update engagement with links
    update_data = {}
    if manager_id:
        update_data["managerId"] = manager_id
    if community_id:
        update_data["communityId"] = community_id
    
    if update_data:
        print(f"Updating engagement with: {update_data}")
        crm.update_engagement(engagement_id, update_data)
        results["engagement"]["updated"] = update_data
    
    # 5. Create contacts
    for contact in community_data.get("contacts", []):
        email = contact.get("email")
        name = contact.get("name", "")
        title = contact.get("title", "")
        
        if not email:
            continue
        
        # Check if exists
        existing = crm.search_people(email=email)
        if existing:
            print(f"Contact exists: {email}")
            continue
        
        # Parse name
        name_parts = name.split(" ", 1)
        first_name = name_parts[0] if name_parts else "Unknown"
        last_name = name_parts[1] if len(name_parts) > 1 else ""
        
        try:
            print(f"Creating contact: {name} ({email})")
            person = crm.create_person(first_name, last_name, email, title)
            results["contacts_created"].append({"name": name, "email": email, "id": person.get("id")})
        except Exception as e:
            results["errors"].append(f"Failed to create {email}: {str(e)}")
    
    # 6. Create notes
    notes_to_create = []
    short_name = community_name.split()[0] if community_name else "Community"  # e.g., "Carleton" or "CWV"
    
    # One Point Team note
    if team:
        team_md = "# One Point Team\n\n"
        for member in team:
            team_md += f"- **{member.get('name', '')}**: {member.get('role', '')}\n"
        team_md += f"\n*Auto-imported from Reference Guide PPTX on {datetime.now().strftime('%Y-%m-%d')}*"
        notes_to_create.append((f"{short_name}: One Point Team", team_md))
    
    # Goals note
    goals = community_data.get("goals", [])
    if goals:
        goals_md = "# Client Goals\n\n"
        for goal in goals[:10]:  # Limit
            goals_md += f"- {goal}\n"
        goals_md += f"\n*Auto-imported from Reference Guide PPTX*"
        notes_to_create.append((f"{short_name}: Client Goals", goals_md))
    
    # Market Analysis note
    market = community_data.get("market_analysis", {})
    demand = market.get("demand_summary", [])
    if demand:
        market_md = "# Market Analysis\n\n"
        for item in demand[:5]:
            market_md += f"- {item[:200]}...\n" if len(item) > 200 else f"- {item}\n"
        market_md += f"\n*Auto-imported from Reference Guide PPTX*"
        notes_to_create.append((f"{short_name}: Market Analysis", market_md))
    
    # Development note
    dev = community_data.get("development", {})
    if dev.get("vulnerabilities") or dev.get("opportunities"):
        dev_md = "# Development Analysis\n\n"
        if dev.get("vulnerabilities"):
            dev_md += "## Vulnerabilities\n"
            for v in dev["vulnerabilities"][:3]:
                dev_md += f"- {v[:150]}...\n" if len(v) > 150 else f"- {v}\n"
        if dev.get("opportunities"):
            dev_md += "\n## Opportunities\n"
            for o in dev["opportunities"][:3]:
                dev_md += f"- {o[:150]}...\n" if len(o) > 150 else f"- {o}\n"
        dev_md += f"\n*Auto-imported from Reference Guide PPTX*"
        notes_to_create.append((f"{short_name}: Development Analysis", dev_md))
    
    # Presentations Log note
    presentations = community_data.get("presentations", [])
    if presentations:
        pres_md = "# Presentations Log\n\n"
        for p in presentations:
            pres_md += f"- **{p.get('date', 'Unknown')}** (Slide {p.get('slide', '?')})\n"
        pres_md += f"\n*Auto-imported from Reference Guide PPTX*"
        notes_to_create.append((f"{short_name}: Presentations Log", pres_md))
    
    # Next Steps note
    next_steps = community_data.get("next_steps", [])
    if next_steps:
        steps_md = "# Next Steps\n\n"
        for step in next_steps[:5]:
            steps_md += f"- {step}\n"
        steps_md += f"\n*Auto-imported from Reference Guide PPTX*"
        notes_to_create.append((f"{short_name}: Next Steps", steps_md))
    
    # Create and link notes
    for title, markdown in notes_to_create:
        try:
            print(f"Creating note: {title}")
            note = crm.create_note(title, markdown)
            note_id = note.get("id")
            results["notes_created"].append({"title": title, "id": note_id})
            
            # Link to engagement
            if note_id:
                crm.link_note_to_engagement(note_id, engagement_id)
                results["notes_linked"].append(note_id)
                print(f"  → Linked to engagement")
        except Exception as e:
            results["errors"].append(f"Failed to create note '{title}': {str(e)}")
    
    return results


def main():
    parser = argparse.ArgumentParser(description="Sync community data to Twenty CRM")
    parser.add_argument("--file", "-f", help="JSON file with community data (or use stdin)")
    parser.add_argument("--dry-run", "-n", action="store_true", help="Don't actually create records")
    
    args = parser.parse_args()
    
    # Get Twenty credentials
    api_url = os.environ.get("TWENTY_API_URL")
    api_token = os.environ.get("TWENTY_API_TOKEN")
    
    if not api_url or not api_token:
        print("Error: TWENTY_API_URL and TWENTY_API_TOKEN required", file=sys.stderr)
        print("Set these environment variables or configure in clawdis.json", file=sys.stderr)
        sys.exit(1)
    
    # Load data from file or stdin
    if args.file:
        with open(args.file) as f:
            data = json.load(f)
    else:
        data = json.load(sys.stdin)
    
    # Initialize CRM client
    crm = TwentyCRM(api_url, api_token)
    
    # Sync
    results = sync_community_to_twenty(data, crm, dry_run=args.dry_run)
    
    # Output results
    print("\n" + "=" * 50)
    print("SYNC RESULTS")
    print("=" * 50)
    print(json.dumps(results, indent=2))
    
    # Exit with error if there were problems
    if results["errors"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
